export default {
  book: {
    GET_BOOK_REQUESTED: "GET_BOOK_REQUESTED",
    GET_BOOK_SUCCEED: "GET_BOOK_SUCCEED",
    GET_BOOK_FAILED: "GET_BOOK_FAILED",
    UPDATE_BOOK: "UPDATE_BOOK",
    CREATE_OR_EDIT_BOOK: "CREATE_OR_EDIT_BOOK",
  },
};
